### ISSUE TITLE
Cannot import sortorder

### ISSUE THREAD

**Issue by xaviershay** [fvbommel/util#1]
I suspect something isn't set up right with your canonical URL?

```
> go get vbom.ml/util/sortorder
package vbom.ml/util/sortorder: unrecognized import path "vbom.ml/util/sortorder"
> git clone https://vbom.ml/util/sortorder /tmp/arstrst  
Cloning into '/tmp/arstrst'...
fatal: unable to access 'https://vbom.ml/util/sortorder/': Server aborted the SSL handshake
```

Pretty sure this _used_ to work.

**Comment by fvbommel** [comment]
The server isn't set up for https unfortunately. Try

```
go get -insecure vbom.ml/util/sortorder
```

instead.

I think it used to automatically fall back to http when https didn't work,
but I guess the Go team changed that. Good for security, but bad for user
experience :(.

Sorry for the inconvenience,

```
Frits van Bommel
```

**Comment by xaviershay** [comment]
Ah, that makes sense. Would you consider a) installing HTTPS, or b) reverting the canonical import path so I can use a secure github URL?

**Comment by fvbommel** [comment]
Yeah, that makes sense. I just disabled the canonical import path
enforcement.

**Comment by fvbommel** [comment]
Just a heads-up: I just got my vanity import to support https, so I
re-enabled the canonical import path enforcement.

**Comment by xaviershay** [comment]
fantastic, thank you!

**Comment by fvbommel** [comment]
Oh, I didn't realize this was an issue :). I was just replying by mail...
