### ISSUE TITLE
unable to deduce repository and source type for "vbom.ml/util"

### ISSUE THREAD

**Issue by smecsia** [fvbommel/util#5]
Something's weird happening with vbom.ml domain that is one of transitive deps of our project's dependencies. As a result we can see the following error when using dep:
```
unable to deduce repository and source type for "vbom.ml/util": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://vbom.ml/util?go-get=1": Get http://vbom.ml/util?go-get=1: dial tcp: lookup vbom.ml on 127.0.0.11:53: server misbehaving
```
If you try commands `dig @8.8.8.8 vbom.ml` and `dig @1.1.1.1 vbom.ml`, you'd see they give different results. One works (Cloudflare) and one doesn’t (Google). 

Looks like this isn't the first time when the issue occurs:  https://github.com/kubernetes/kops/issues/5300

@fvbommel I understand this repository is very old and most likely isn't properly maintained and we can mitigate the issue on our side. But may be you could investigate it?

**Comment by fvbommel** [comment]
Actually, both of those `dig` commands give the same result for me. And I just did a `go get vbom.ml/util` after deleting my package cache and it worked just fine for me (using go 1.13).

I was also actually never notified of that other issue, so this is the first I'm hearing about this and I won't have time to look at it until tonight (CEST).

**Comment by fvbommel** [comment]
I've removed the vanity import path due to another issue (#6).
Please use `github.com/fvbommel/util` as the import path instead, that way you're no longer dependent on my domain name.

**Comment by fvbommel** [comment]
Actually, since we're updating import paths anyway, if you're using `sortorder` please use `github.com/fvbommel/sortorder` instead.
