### ISSUE TITLE
can't resolve vbom.ml/util dependency

### ISSUE THREAD

**Issue by dhiller** [fvbommel/util#6]
When trying to resolve dependency we receive:

go: vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787: unrecognized import path "vbom.ml/util" (parse https://vbom.ml/util?go-get=1: no go-import meta tags ())

This is i.e. the case when trying to go build stuff below `robots` from [kubernetes/test-infra](https://github.com/kubernetes/test-infra).

curl delivers this:

```
curl 'https://vbom.ml/util?go-get=1'
Go 1.9 is no longer available.  Please refer to https://goo.gl/aESk5L for more information.
```

Workaround was using 

`replace vbom.ml/util => github.com/fvbommel/util v0.0.0-20180919145318-efcd4e0f9787`

**Comment by dhiller** [comment]
Got the workaround from here: https://github.com/fromanirh/performance-addon-operators/commit/e94312e563a3323e5ea8e49b86c1ffa80d0330f7

**Comment by khuddlefish** [comment]
We just experienced the same issue and mitigated it the same way. It seems like it would be easier to just use the `github.com/fvbommel/util` import path instead of the `vbom.ml/util` one?

**Comment by fvbommel** [comment]
Sorry about this, I was running the site from App Engine and had some issues updating to newer Go versions (not Go-related, App Engine-related).

I've removed the vanity imports so you can just use the `github.com/fvbommel/util` import path now.

**Comment by fvbommel** [comment]
Actually, since we're updating import paths anyway, if you're using `sortorder` please use `github.com/fvbommel/sortorder` instead.

**Comment by khuddlefish** [comment]
Awesome thanks for the update :)
